from django.conf.urls import include, url
from PlotDistribution.views import *

urlpatterns = [
    url(r'^home$',home),
    url(r'^Plot',Plot),
    url(r'^ClickPlot',ClickPlot),
    url(r'^clickShowAnomalyOverall',clickShowAnomalyOverall),
    url(r'^ShowAnomalies',ShowAnomalies),
    url(r'^Egonet',Egonet),
    url(r'^GetEgonet',GetEgonet),
    url(r'^GetAdj',GetAdj),
    url(r'^DeleteMatrixFiles',DeleteMatrixFiles),
    url(r'^AdjShowReverse',AdjShowReverse),
    url(r'^Heatmap',Heatmap),
    url(r'^DBPlot',DBPlot),
    url(r'^GetPlotData',GetPlotData),
    url(r'^searchNumberById',searchNumberById),
    url(r'^searchById',searchById),
    url(r'^searchByNumber',searchByNumber),
    url(r'^MultiPlots$',MultiPlots),
    url(r'^MultiPlots_soc_Slashdot0811$',MultiPlots_soc_Slashdot0811),
    url(r'^MultiPlots_soc_Slashdot0811_HeatMap$',MultiPlots_soc_Slashdot0811_HeatMap),
    url(r'^MultiPlots_soc_Slashdot0902$',MultiPlots_soc_Slashdot0902),
    url(r'^MultiPlots_soc_Slashdot0902_HeatMap$',MultiPlots_soc_Slashdot0902_HeatMap),
    url(r'^MultiPlots_test',MultiPlots_test),
    url(r'^MultiPlots_wiki_Vote$',MultiPlots_wiki_Vote),
    url(r'^MultiPlots_wiki_Vote_HeatMap$',MultiPlots_wiki_Vote_HeatMap),
    url(r'^MultiPlots_tmp_ID_processed$',MultiPlots_tmp_ID_processed),
    url(r'^MultiPlots_tmp_ID_processed_HeatMap$',MultiPlots_tmp_ID_processed_HeatMap),
    url(r'^MultiPlots_tmp1_ID_processed$',MultiPlots_tmp1_ID_processed),
    url(r'^MultiPlots_tmp1_ID_processed_HeatMap$',MultiPlots_tmp1_ID_processed_HeatMap),
    url(r'^MultiPlots_tmp2_ID_processed$',MultiPlots_tmp2_ID_processed),
    url(r'^MultiPlots_tmp2_ID_processed_HeatMap$',MultiPlots_tmp2_ID_processed_HeatMap),
    url(r'^MultiPlots_tmp2_ID_final_HeatMap$',MultiPlots_tmp2_ID_final_HeatMap),
    url(r'^MultiPlots_phonePage_edge_HeatMap$',MultiPlots_phonePage_edge_HeatMap),
    url(r'^MultiPlots_phonePage_edge_w_HeatMap$',MultiPlots_phonePage_edge_w_HeatMap),

    url(r'^MultiPlots_mon_1_rt_p_reorder_HeatMap$',MultiPlots_mon_1_rt_p_reorder_HeatMap),
]
